# Generated by Django 3.2 on 2022-07-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
