# Generated by Django 3.2 on 2022-07-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='count',
        ),
    ]
