# Generated by Django 3.2 on 2022-07-10 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20220710_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.CharField(max_length=255, verbose_name='博客地址')),
                ('summary', models.CharField(max_length=128, verbose_name='简介')),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='dp',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default=1, max_length=32, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='B2G',
        ),
        migrations.DeleteModel(
            name='Boy',
        ),
        migrations.DeleteModel(
            name='Depart',
        ),
        migrations.DeleteModel(
            name='Girl',
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.userinfo'),
        ),
    ]
