# Generated by Django 3.2 on 2022-07-10 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20220710_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='new_depart',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='d2', to='app01.depart', verbose_name='新部门'),
        ),
    ]
