# Generated by Django 3.2 on 2022-07-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='标题')),
            ],
        ),
        migrations.AlterField(
            model_name='depart',
            name='title',
            field=models.CharField(max_length=32, unique=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(db_index=True, max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterModelTable(
            name='depart',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table=None,
        ),
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='标题')),
                ('b', models.ManyToManyField(to='app01.Boy')),
            ],
        ),
    ]
