# Generated by Django 3.2 on 2022-07-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='od',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
